### ISSUE TITLE
Tracking: Computer game mode (Stockfish)

### ISSUE THREAD

**Issue by nelson137** [nelson137/gambit#41]
Add a game mode -- separate from Analysis (solo mode) and Co-op (multiplayer mode) -- for playing against Stockfish, "the computer".

This game mode has its own button on the main menu. The Stockfish evaluation bar is not visible during gameplay.

## Tasks

- [x] Initial Stockfish integration (#10)
    - Add a build script that installs Stockfish
    - Ensure the executable always gets installed for all users, not just those building the game from source
    - Launch the executable and implement basic communication
    - Stockfish plays as black
- [ ] User can play as either white or black
    - Board is correctly oriented at start of game and does not flip afterward
- [ ] Stockfish correctly plays as the other color
    - Correctly handles the cases where Stockfish must make the first move (i.e. it can't just listen for `MovePiece` component removal, it needs to be prompted to move based on the game state and whose turn it is)
- [ ] Main menu has a dedicated button e.g. "Play Computer"
    - Stockfish only plays in this game mode
    - User's color is chosen randomly
